@startuml アクティビティ図

start
:何も選択されてない;
if(クリック) then (マウスの位置に要素がある)
    :要素を選択しつかむ;
else (要素がない)
    :何もしない;
endif
:要素が1つ選択されてる;
if(クリック) then (要素がある)
    if(コントロールが) then (押された)
        :要素を追加しつかむ;
    else (押されてない)
        if(要素が) then(すでに選択されている)
            :要素をつかむ;
        else (まだ選択されていない)
            :選択を切り替えつかむ;
        endif
    endif
else (要素がない)
    :全選択解除;
endif
end

@enduml